newsfeed/core/views.py
#core // views.py
from newsfeed.models import News
from flask import render_template, request, Blueprint

core = Blueprint('core', __name__)

@core.route('/')
def index():
    page = request.args.get('page',1,type=int)
    news_feed = News.query.order_by(News.date.desc()).paginate(page=page, per_page=10)

    return render_template('index.html', news_feed=news_feed)


@core.route('/info')
def info():
    return render_template('info.html')

newsfeed/feeds/views.py
from flask import render_template, flash, url_for, redirect, request, Blueprint
from flask_login import current_user, login_required
from newsfeed import db
from newsfeed.models import News
from newsfeed.feeds.forms import NewsFeedForm


news_feed_b = Blueprint('news_feed', __name__)

#Creating blog post
@news_feed_b.route('/create', methods=['GET','POST'])
@login_required
def create_post():
    form = NewsFeedForm()

    if form.validate_on_submit():

        news_feed = News(title=form.title.data, text=form.text.data, user_id=current_user.id)

        db.session.add(news_feed)
        db.session.commit()

        return redirect(url_for('core.index'))
    return render_template('create_post.html', form=form)


#updating blog post

@news_feed_b.route("/<int:news_feed_id>/update", methods=['GET','POST'])
@login_required
def update(news_feed_id):
    news_feed = News.query.get_or_404(news_feed_id)

    if news_feed.author != current_user:
        return redirect(url_for('error_pages.error_403'))

    form = NewsFeedForm()

    if form.validate_on_submit():
        news_feed.title = form.title.data
        news_feed.text = form.text.data
        db.session.commit()

        return redirect(url_for('news_feed.news_feed',news_feed_id = news_feed_id))

    elif request.method == 'GET':
        form.title.data = news_feed.title
        form.text.data = news_feed.text

    return render_template('create_post.html',title='Updating', form=form)



#deleting blog post
@news_feed_b.route('/<int:news_feed_id>/delete', methods=['GET','POST'])
@login_required
def delete_post(news_feed_id):
    news_feed = News.query.get_or_404(news_feed_id)

    if news_feed.author != current_user:
        return redirect(url_for('error_pages.error_403'))

    db.session.delete(news_feed)
    db.commit()
    flash("Blog post deleted")
    return redirect(url_for('core.index'))


#viewing blog post
@news_feed_b.route('/<int:news_feed_id>')
def news_feed(news_feed_id):
    news_feed = News.query.get_or_404(news_feed_id)
    return render_template('news_feed.html', title=news_feed.title, date=news_feed.date, post=news_feed)

newsfeed/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from newsfeed import db
from newsfeed.models import User, News
from newsfeed.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from newsfeed.users.picture_handler import add_profile_pic


users = Blueprint('users', __name__)

@users.route('/register',methods=['GET','POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('Thanks for registration!')
        return redirect(url_for('users.login'))

    return render_template('register.html',form=form)


@users.route('/login', methods=['GET','POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:
            login_user(user)
            flash('Login successful')

            next = request.args.get('next')

            if next == None or not next[0]=='/':
                next = url_for('core.index')

            return redirect(next)
    return render_template('login.html', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('core.index'))


@users.route('/account', methods=['GET','POST'])
@login_required
def account():
    form = UpdateUserForm()

    if form.validate_on_submit():

        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data, username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User Account Updated!')
        return redirect(url_for('users.account'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image= url_for('static', filename = 'profile_pics/'+ current_user.profile_image)
    return render_template('account.html', profile_image=profile_image, form=form)

@users.route('/<username>')
def user_posts(username):
    page = request.args.get('page',1,type=int)
    user = User.query.filter_by(username=username).first_or_404()
    news_feed = News.query.filter_by(author=user).order_by(News.date.desc()).paginate(page=page, per_page=5)
    return render_template('user_news_feed.html', news_feed=news_feed, user=user)

newsfeed/templates/account.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron">
    <div align="center">
        <h1> Welcome! {{ current_user.username }} </h1>
        <img align="center" src="{{ url_for('static', filename='profile_pics/'+ current_user.profile_image) }}">
    </div>
</div>

<div class="container">

<form method="POST" action="" enctype="multipart/form-data">

     {{ form.hidden_tag() }}

    <div class="form-group">
       {{ form.email.label(class='form-group') }} {{ form.email(class='form-control') }} <br>
    </div>
     <div class="form-group">
       {{ form.username.label(class='form-group') }} {{ form.username(class='form-control') }} <br>
    </div>
     <div class="form-group">
        {{ form.username.label(class='form-group') }} {{ form.username(class='form-control') }} <br>
    </div>
     <div class="form-group">
        {{ form.picture.label(class='form-group') }} {{ form.picture(class='form-control') }} <br>
    </div>
    <div class="form-grout">
        {{ form.submit(class='btn btn-primary') }}
    </div>

</form>

</div>

{% endblock %}

newsfeed/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
</head>
<body>

<ul class="navbar navbar-expand-lg navbar-light bg-light">

    <li class="nav-link"> <a href="{{ url_for('core.index') }}">Home</a> </li>

    <li class="nav-link"> <a href="{{ url_for('core.info') }}">About</a> </li>

    {% if current_user.is_authenticated %}

    <li class="nav-link"> <a href="{{ url_for('users.logout') }}">Logout</a> </li>

    <li class="nav-link"> <a href="{{ url_for('users.account') }}">Account</a> </li>

    <li class="nav-link"> <a href="{{url_for('news_feed.create_post')}}">Create Post</a> </li>

    {% else %}
    <li class="nav-link"> <a href="{{ url_for('users.login') }}">Login</a> </li>

    <li class="nav-link"> <a href="{{ url_for('users.register') }}">Register</a> </li>

    {% endif %}

</ul>

<div class="container">

{% block content %}

{% endblock %}

</div>


</body>
</html>

newsfeed/templates/create_post.html
{% extends "base.html" %}
{% block content %}

<div class="container">
    <form class="form-group", method="post">

        {{form.hidden_tag()}}

        <div class="form-group">
            {{ form.title.label(class='form-control-label') }}
            {{ form.title(class='form-control form-control-lg') }}
        </div>

        <div class="form-group">
            {{ form.text.label(class='form-control-label') }}
            {{ form.text(class='form-control form-control-lg') }}
        </div>

        <div class="form-group">
            {{ form.submit(class='btn btn-outline-info') }}
        </div>

    </form>

</div>

{% endblock %}

newsfeed/templates/index.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron">
    <h1> Newsfeed </h1>
</div>

<div class="container">

    {% for post in news_feed.items %}

    <div class="card">
        <div class="card-body">
            <h2> <a class="card-title" href="{{ url_for('news_feed.news_feed', news_feed_id=post.id) }}">{{post.title}}</a> </h2>
            Posted by: {{ post.author.username }}
            <p>Published on: {{ post.date.strftime('%Y-%m-%d') }}</p>
            <a class="btn btn-primary" href="{{ url_for('news_feed.news_feed', news_feed_id=post.id) }}">Read feed</a>
        </div>
    </div>

    {% endfor %}

</div>

<nav aria-label="Page Navigation Example">
    <ul class="pagination justify-content-center">

        {% for page_number in news_feed.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}

            {% if news_feed.page == page_num %}

                <li class="page-item disabled"> <a class="page-link" href="{{url_for('core.index', page=page_num)}}">{{page_num}}</a></li>

            {{ else }}

                <li class="page-item"> <a class="page-link" href="{{url_for('core.index', page=page_num)}}">{{page_num}}</a></li>

            {% endif %}

        {% endfor %}

    </ul>
</nav>


{% endblock %}

newsfeed/templates/info.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron">
    <h1> About us</h1>
    <p> lorem epsum.... dolor sit...</p>
</div>

{% endblock %}

newsfeed/templates/login.html
{% extends "base.html" %}
{% block content %}
<div class="container">
<form method="POST">

    {{ form.hidden_tag() }}
    <div class="form-group">
       {{ form.email.label(class='form-group') }} {{ form.email }}
    </div>

    <div class="form-group">
        {{ form.password.label(class='form-group') }} {{ form.password }}
    </div>

    <div class="form-group">
      {{ form.submit(class='btn btn-primary') }}
    </div>


</form>
</div>

{% endblock %}

newsfeed/templates/news_feed.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron">
    <h1> {{post.title}} </h1>
    <h2> Posted by: {{ post.author.username }} </h2>
    <h3>Published: {{ post.date.strftime('%M %d, %Y') }} </h3>
    <p>{{ post.text }}</p>

    {% if post.author==current_user %}
    <div >
        <a href="{{ url_for('news_feed.update', news_feed_id=post.id) }}">Update</a>
        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal" >Delete</button>
    </div>

    {% endif %}
</div>

<div class="modal" tabindex="-1" role="dialog" id="del_modal">
    <div class="modal-dialog" role="dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Delete Feed?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <div class="modal-body">
                    <p>Are you sure you want to delete the post?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

                    <form action="{{ url_for('news_feed.delete_post', news_feed_id=post.id) }}">
                        <input class="btn btn-danger" type="submit" value="Delete" >
                    </form>

                    <button type="button" class="btn btn-primary">Delete</button>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock %}

newsfeed/templates/register.html
{% extends "base.html" %}
{% block content %}

<div class="container" margin-left="50px">

<form method="POST" >

    {{ form.hidden_tag() }}
    <div class="form-group">
    {{ form.email.label(class='form-group') }} {{ form.email }}
    </div>

     <div class="form-group">
    {{ form.username.label(class='form-group') }} {{ form.username }}
    </div>

     <div class="form-group">
     {{ form.password.label(class='form-group') }} {{ form.password }}
     </div>

     <div class="form-group">
    {{ form.pass_confirm.label(class='form-group') }} {{ form.pass_confirm }}
    </div>

     <div class="form-group">
     {{ form.submit(class='btn btn-primary') }}
     </div>

 </form>
</div>

{% endblock %}

newsfeed/templates/user_news_feed.html
{% extends "base.html" %}
{% block content %}
<div class="container">

  <div class="jumbotron">
    <div align="center">
        <h1>{{user.username}}</h1>
        <img src="{{ url_for('static', filename='profile_pics/' + user.profile_image) }}">

    </div>
  </div>


{% for post in news_feed.items %}
    <h2> <a href="{{ url_for('news_feed.news_feed', blog_post_id=post.id) }}">{{post.title}}</a> </h2>
    Posted by: <a href="{{ url_for('users.user_post', username=post.author.username)}}"> {{ post.author.username }} </a>
    <p class="text-muted">Published on: {{ post.date.strftime("%Y-%m-%d") }}</p>
    <br>
    <p> {{post.text}} </p> <br>

{% endfor %}

<nav aria-label="Page Navigation Example">
    <ul class="pagination justify-content-center">

        {% for page_number in news_feed.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}

            {% if news_feed.page == page_num %}

                <li class="page-item disabled"> <a class="page-link" href="{{url_for('users.user_news', username=user.username, page=page_num)}}">{{page_num}}</a></li>

            {{ else }}

                <li class="page-item"> <a class="page-link" href="{{url_for('users.user_news', username=user.username, page=page_num)}}">{{page_num}}</a></li>

            {% endif %}

        {% endfor %}

    </ul>
</nav>

</div>

{% endblock %}